### ISSUE TITLE
«Show on third party application» with multiple selected demos sends only one demo multiple times actually

### ISSUE THREAD

**Issue by MaxKade** [akiver/CSGO-Demos-Manager#196]
**Steps to reproduce**
1. Open app.
2. Select multiple demos.
3. Click on «Show on third party application».
4. Select csgostats.gg and share.

**Expected result**
App will send all selected demos to csgostats.gg.

**Actual result**
It sends only first select demo multiple times.

**Comment by zp** [comment]
Can confirm.

It looks like bug is at [Line 1734](https://github.com/akiver/CSGO-Demos-Manager/blob/1738cdb06b073831b150f5676477f829da3e038d/Manager/ViewModel/Demos/DemoListViewModel.cs#L1734) in DemoListViewModel.cs

It's using the sharecode variable for the original selected item at [Line 1724](https://github.com/akiver/CSGO-Demos-Manager/blob/1738cdb06b073831b150f5676477f829da3e038d/Manager/ViewModel/Demos/DemoListViewModel.cs#L1724) instead of creating a new / updating the variable in the loop.
