### ISSUE TITLE
Player kills calculated incorrectly for some matches

### ISSUE THREAD

**Issue by ReagentX** [akiver/CSGO-Demos-Manager#233]
Example demo: https://www.hltv.org/matches/2312362/sk-vs-penta-pgl-major-krakow-2017

The scoreboard says he has 34 kills, however, he had 36 kills and a teamkill. The `Kills` sheet and the `Kill Matrix` sheet in the Excel export have the correct numbers, however, the scoreboard is wrong which means rating, K/D, etc are all wrong as well.

**Comment by Cookieseller** [comment]
The problem here is that teamkills are subtracted twice, coldzera and HS both have one tk and both their scores are wrong. 
OnKillsCollectionChanged calculates the killcount by taking all non teamkills via 
``Kills.Count(k => k.KilledSide != k.KillerSide)``
and then subtracts the teamkills from that, even though they have already been filtered out.
Removing the subtraction will fix the problem.

**Comment by Cookieseller** [comment]
I rethought and found this to be correct behaviour. Coldzera has only 35 opponent kills, the 37th kill is a teamkill. Valve counts teamkills as negative kills, meaning he would have 34 kills ingame. Hltv however does not teamkills as negative, thats why he has 35 kills on the match page but is displayed as having 34 kills ingame. 
So as far as i can tell the kills are calculated correctly as opponent kills - team kills.
