### ISSUE TITLE
Video generated by FFmpeg cannot be imported to Premiere Pro?

### ISSUE THREAD

**Issue by Zero-Tang** [akiver/CSGO-Demos-Manager#395]
Premiere Pro CS6 treats the resolution as 16-160 instead of 1920-1080.
I assume parameters passed to ffmpeg should be revised to solve this issue. Maybe use "-crf" as the quality option could solve it?

**Comment by akiver** [comment]
I never tested Premiere Pro, maybe the codec `libx264` is not supported?
You could try manually with an other codec (copy / paste the cli from the app and change the code parameter).  

Otherwise, since it's for video editing I recommend you to use an uncompressed video using VirtualDub instead of FFMpeg

**Comment by Zero-Tang** [comment]
I find out that Premiere Pro CC 2019 supports video generated by ffmpeg. Yet it supports Windows 10 only. This is a sad fact that I don't like Windows 10.
Then I suppose I should have a large disk to store VirtualDub-generated videos.
Closing issue.
