### ISSUE TITLE
Output JSON files programmatically

### ISSUE THREAD

**Issue by psychosopher** [akiver/CSGO-Demos-Manager#433]
Hi~
I want to do some complicated analysis based on the JSON or Excel data exported.

The issue is that, my analysis is based on Python and I want to update the analysis result automatically, using many demo files. Exporting by hand every update may cost a lot of time.

Thus, I hope there is a way to programmatically export the JSON or Excel data, so that I can further analysis them in an easier way. I was also wondering whether there is an existing way to do that (e.g., python API, or command line).

Thank you!

**Comment by ESBUINBOO** [comment]
Would be an insane feature boys! I have the same "issue" x)

**Comment by lilgandhi1199** [comment]
@akiver I agree would be very nice launch option (Download+Analyze all available demos and export to JSON)
But I don't mind doing it by hand for each of my games.

in v3 I hope you add the heatmap player positions aswell which I asked about last year.
I just commented and told you more about how helpful it would be for me because my code is terribly terribly slow extracting it myself from the original demo file using CSGO's open source demoinfo program!
