### ISSUE TITLE
csgo demos manager not opening demos, not detecting them in folder

### ISSUE THREAD

**Issue by kawtunow** [akiver/CSGO-Demos-Manager#442]
Hi there,
my csgo demos manager is not opening any of my demos, when I open the demo with demos manager it just takes me to the main screen with the message no demos found please help as this is very frustrating

**Comment by jayfunk** [comment]
I just had this issue. I think it might be because the location that CSGO puts the demos by default has changed. CSGO Demos Manager looks for them at `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo` but the actual folder is `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo\replays`. You can add this folder in settings.

**Comment by akiver** [comment]
As mentioned by @jayfunk make sure to add the `replays` folder if it's not available from the demos list and then select it to see demos inside it https://www.csgo-demos-manager.com/docs/general#empty-list
