### ISSUE TITLE
Kast

### ISSUE THREAD

**Issue by midnightcatzz** [akiver/CSGO-Demos-Manager#458]
is there anyway to view Kast%?

**Comment by Kiziev** [comment]
> is there anyway to view Kast%?

@midnightcatzz found?

**Comment by 3vaLpwner** [comment]
KAST is hard to calculate without watching a demo.
Since it caluclates this way:
![изображение](https://user-images.githubusercontent.com/80704041/112748798-f57f7680-8fc6-11eb-816e-e503ea8ca4d6.png)
So you need 
(Kills + Assists + ( Rounds - Deaths ) + Trades*) / Rounds
*Not exactly understood which trade because in CSGODM you can find trade kills and trade deaths.
Export to XLS => Do math. Ez.

**Comment by 3vaLpwner** [comment]
> 
> 
> Since it caluclates this way:
> ![изображение](https://user-images.githubusercontent.com/80704041/112748798-f57f7680-8fc6-11eb-816e-e503ea8ca4d6.png)
> So you need
> (Kills + Assists + ( Rounds - Deaths ) + Trades*) / Rounds
> *Not exactly understood which trade because in CSGODM you can find trade kills and trade deaths. I think it's about deaths here.
> Export to XLS => Do math. Ez.

Example: last game NAVI vs Gambit on ESL (Group C, all 3 maps analyzed):
![изображение](https://user-images.githubusercontent.com/80704041/112749329-5e1c2280-8fca-11eb-9f38-285ec7a58705.png)

**Comment by 3vaLpwner** [comment]
Actually, calculating KAST and Impact is most painful stuph cause u really don't know how good was player's performance only by stats. Lots of future work in here.

**Comment by akiver** [comment]
Added in version 2.14.0
