### ISSUE TITLE
Recoding a movie does not show who is talking

### ISSUE THREAD

**Issue by somuchtyler** [akiver/CSGO-Demos-Manager#496]
Even though you can hear people talking during the demo, using the "Movie" function in CSGO Demos Manager will make a video where it won't show the names of the people who are talking. Is there a way to turn on showing the names of the people who are talking?

**Comment by sheharyaar** [comment]
@somuchtyler Does playing the demo file directly in the game show the names of people talking?

**Comment by akiver** [comment]
It's because the default cfg used to record demos includes `cl_draw_only_deathnotices 1`.
![2022-04-17 16_46_57-](https://user-images.githubusercontent.com/1842524/163719682-16da273a-b424-4cc6-9311-2f03746e7535.png)

You have to remove it to see the UI game indicators but it will also display others UI stuff such as the radar.
