### ISSUE TITLE
Date and time on detailed Match page

### ISSUE THREAD

**Issue by Daxelinho** [akiver/CSGO-Demos-Manager#503]
If you look at the detailed information on a match on the left are a few infos like "Filename", "Map", "Type", "Hostname", etc.

I would really appreciate if you could add the time and date of the match to this list.

**Comment by SuperArwenAntoinette** [comment]
I think this should be a feature and not an issue, I also don't know if the time of the match can be parsed coming from the .dem file or if we should be calling a 3rd party to get the time and date of the match.  Aside from that, date and time are relative to the timezone using the application so that should be considrered as well.

**Comment by Daxelinho** [comment]
I'm new to GitHub, honestly I haven't found a different way of proposing this idea. Can I change it somehow?

In the overview the time and date is displayed, as well. That information could be taken over to the detailed match screen.
If I observed it correctly, time and date in the current version for matchmaking demos is the true time the match was played and on third party demos like Faceit the time is the creation time of the .dem file.

**Comment by SuperArwenAntoinette** [comment]
Yes, If you find a way to do it then you can change it. Make a pull request and have the author reviewed your PR.
