### ISSUE TITLE
The program telling me the user selected is not present in this demo (it is)

### ISSUE THREAD

**Issue by tomaszdubiel18** [akiver/CSGO-Demos-Manager#526]
Hello.
The program telling me the user selected is not present in this demo (it is).
My steam profile: https://steamcommunity.com/profiles/76561198387583747/
Game demo to download:
steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-KoTyK-yZT75-d2V3F-CC82s-ECBcO

**Comment by akiver** [comment]
I assume you are trying to watch player highlights from the demo list.

![message](https://user-images.githubusercontent.com/1842524/168755502-f3fb1b8f-634d-48f5-8ff5-c4659c19e2be.png)

If you see this message, it's because of one of the following reasons:
- The demo has not been analyzed
- The current focused account is not set or is not in the demo

For the second possibility, make sure that the account has been added **and** focused from the settings:

![account](https://user-images.githubusercontent.com/1842524/168755520-9532f6e8-b97a-4c43-a7e8-1dc0de82e504.png)
