### ISSUE TITLE
Official Discord Server?

### ISSUE THREAD

**Issue by SteveBox0** [akiver/CSGO-Demos-Manager#545]
Any chance of an official discord server for CSGO Demos Manager? It would be a great way for the user-base to self troubleshoot issues together, review demos, etc.

**Comment by akiver** [comment]
Hi, I already thought about it a long time ago, and I prefer to stick with GitHub for the following reasons:

- Users would have to create an account and join a channel to access resources that should be free and public
- Things get lost easily on Discord (the "forum" thing helps here, but nothing prevents users from asking in a chat room instead of a post)
- No SEO with Discord
- Requires constant administration
- It would become an issue tracker

I will enable the GitHub "Discussions" tab when the V3 is out.
Thank you for your understanding.
