### ISSUE TITLE
Nade Trajectory

### ISSUE THREAD

**Issue by ZjzMisaka** [akiver/CSGO-Demos-Manager#586]
Is it possible to grab the grenade trajectory from point where it is fired to the point where it explodes?

I'm developing a demo playback software, in order to get the position of the projectile, I read and saved the information of the entire demo file with "parser.ParseToEnd()", so that the WeaponFired event corresponds to the XxxNadeEnded event
This works when reading small demos, but causes OutOfMemoryException when reading large demos.

**Comment by akiver** [comment]
You could save the initial position on `WeaponFired` events and get the final position with `xxxNadeExploded` events (like you seem to do).
About the memory issue, you could use the Visual Studio memory debugger to find what is taking much memory and think of a solution. I guess you are holding too much unnecessary data while parsing the demo.

I'm closing it since it's not a app bug.
