### ISSUE TITLE
Add Nationality of the player in the export of the xlsx file

### ISSUE THREAD

**Issue by Xiguinilster** [akiver/CSGO-Demos-Manager#601]
It would be very useful to create a player database by adding a column that indicates the player's nationality (using the steam id)

**Comment by akiver** [comment]
This feature request will not be implemented because:

- The user's country is not defined by default and has to be by the user, and thus it would be missing in many cases.
- It's not accurate, users can choose a fake country which leads to inaccurate stats.
- I don't want to deal with GDPR regulation
- The app generates stats based on accurate data, it would not be the case here
