### ISSUE TITLE
Request to contribute with POV demo support

### ISSUE THREAD

**Issue by JLysberg** [akiver/CSGO-Demos-Manager#606]
First of all, I would like to thank you for all the effort you have put into creating this tool. It is truly the most comprehensive CSGO demo parser that I am aware of.

Seeing as GOTV demos are more widely used than POV demos in the community, I respect your decision of focusing solely on GOTV. However, a current project of mine would benefit greatly from _some_ minimal implementation of POV demo parsing. I would therefore like to contribute to the continued development of this project by adding such support, if you are open for it.

However, before I do, will you please enlighten me on the "technical reasons" you encountered which led to the decision of excluding POV demos altogether? Did the structure of events and data differ from GOTV to such a degree that all parsing failed? Perhaps data was just so lacking that you figured the effort would be fruitless? Seeing as there are implementations in other frameworks that work (most notably Golang and Node.js), one would think that POV demo support should not be impossible altogether.

In any case, I appreciate any information you could provide on the matter. Thanks!

**Comment by akiver** [comment]
Hi!

POV demos will be supported in the next release, but it can be considered as experimental.

> will you please enlighten me on the "technical reasons" you encountered which led to the decision of excluding POV demos altogether?
- Some entities' creations/updates were ignored when they should not, it was the main problem. You can find the diff in this [commit](https://github.com/akiver/CSGO-Demos-Manager/commit/e463488247ef7786e566495c123f9c4a03695007)
- Entities in POV demos enter/leave the [Potential Visibility Set](https://developer.valvesoftware.com/wiki/PVS) very often. The parser was re-creating entities instead of updating existing entities.
- Since player entities enter/leave the PVS often, we can retrieve player information such as the position only for players in the PVS of the player recording the demo. We don't have this problem with GOTV demos as all players are "visible"
- Some game events are not available in POV demos and vice versa (`player_blind` for example which means flashbang stats will not be available with POV demos)
- The value of properties may be updated several times at the same tick with the exact same values, I have never seen this problem with GOTV demos

Thank you, I hope it answers your questions.

**Comment by JLysberg** [comment]
That is exactly what I was looking for, thank you so much!

I will be sure to look over your recent commits and do some testing when I get the time. Cheers!
