### ISSUE TITLE
Will this work with new Counter Strike 2?

### ISSUE THREAD

**Issue by deadmouse** [akiver/CSGO-Demos-Manager#619]
Will CSGO Demo Manager work with new Counter Strike 2 or an update will be required?

**Comment by 3vaLpwner** [comment]
I am not an author of this but i am doing my own research about that. Actually, there is no much info about CS2 engine, and it's also cannot be collected since there is no function to download any demo from CS2 (have a talk with some guys who have it). And, i guess, no one can say more except Valve, ofc. So we are just waiting.

**Comment by Sonic853** [comment]
Hi, this is a demo I got from playing CS2. The ".info" file can be read by CSGO and CS2, but the ".dem" file can only be read by CS2. Maybe it can provide some help to developers studying replay.

[cs2 replay demo](https://mega.nz/folder/qdIxTI7b#xgfOrfO5M4qTZOb_Qkc3Ow)
