### ISSUE TITLE
The demo may be too old

### ISSUE THREAD

**Issue by playcode001** [akiver/CSGO-Demos-Manager#70]
hi 
An error occured while analyzing the demo 204_galatics-csgo-nerdrage_de_cache.dem.The demo may be too old, if not please send an email with the attached demo.You can find more information on http://csgo-demos-manager.com.

**Comment by playcode001** [comment]
I set a breakpoint，The error message is as follows：
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

**Comment by 0BuRner** [comment]
Can you upload the demo file in the cloud and paste the link ? Will be easier to debug with :) Thx

**Comment by playcode001** [comment]
fnatic vs tsm de dust2 part 1.dem 
fnatic vs tsm de dust2 part 2.dem

**Comment by akiver** [comment]
I assume that the first demo is http://www.hltv.org/?pageid=28&demoid=19953 and the second is http://www.gosugamers.net/counterstrike/tournaments/7548-esl-esea-pro-league-season-2/2049-group-stage/7549-european-division/matches/88583-fnatic-vs-team-solomid.

I don't have errors for the first one. The demo from fnatic vs tsm is splitted into 2 files that's why it doesn't work. It has to be only 1 file.

**Comment by raibutera** [comment]
I'm getting the same issue with any ESEA demos

**Comment by raibutera** [comment]
Update: If I set source manually to "ESEA" then it all works
